### ISSUE TITLE
the supplied environment.yml file doesn't contain the correct jupyter notebook version - conda 

### ISSUE THREAD

**Issue by tyhayward** [defra-data/EODS-API#5]
the supplied jupyter module does not correctly launch from terminal ( - notebook==6.3.0) in a conda environment.

solved through :
conda install -c conda-forge notebook

working: notebook ==6.4.2

jupyter notebook can then be launched correctly from terminal

**Comment by henrywild** [comment]
Hi Ty,

Can you please confirm what OS and terminal you're using? Also, when you say it doesn't launch correctly from terminal, do you mean it doesn't automatically open a browser in that location or that it doesn't provide the 3 urls you can use to connect to the notebook server?

I've just tested it on my end in the Anaconda Powershell Prompt on notebook 6.3.0 from the root repo using these commands and it launched correctly:
`conda env create -f .\environment.yml
conda activate eods
jupyter notebook`

**Comment by tyhayward** [comment]
Hi Henry,

I am using Windows 10 Enterprise. I am using the Python Command Prompt which is installed with the ArcGIS PRO distribution of anaconda, which i believe is a full edition. 

I when I attempted to run jupyter notebook I did the same commands as you have listed. What happened was when I tried to launch jupyter notebook using the above command it instead printed out the help function into the command line and refused to launch. I will try to replicate it shortly

![image](https://user-images.githubusercontent.com/54058249/129553919-1efe2987-99d7-48a4-b7c5-3e8d8d976849.png)

**Comment by henrywild** [comment]
@tyhayward If you try running `conda --version`, does it recognise `conda` as a valid command? I had to add it to my path to get jupyter notebook to run from the standard windows 10 command prompt, and while the anaconda prompt has this exposed by default, I don't know if ArcGIS PRO's Python Command Prompt does.

**Comment by tyhayward** [comment]
Hi @henrywild yes conda is rooted correctly with the Python Command Proompt terminal. conda --version returns 4.9.2 (on my working env.). I am going to create a new environment and try to replicate the original problem.

thanks
ty

**Comment by henrywild** [comment]
Brilliant, thanks @tyhayward

**Comment by tyhayward** [comment]
@henrywild  env modules after installing the environment into a clean build:
`>conda list
# packages in environment at C:\Users\Thayward\AppData\Local\ESRI\conda\envs\eods-test:
#
# Name                    Version                   Build  Channel
affine                    2.3.0                      py_0    conda-forge
argon2-cffi               20.1.0           py38h294d835_2    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bleach                    4.0.0              pyhd8ed1ab_0    conda-forge
boost-cpp                 1.74.0               h54f0996_3    conda-forge
brotlipy                  0.7.0           py38h294d835_1001    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.5.30            h5b45459_0    conda-forge
cairo                     1.16.0            hb19e0ff_1008    conda-forge
certifi                   2021.5.30        py38haa244fe_0    conda-forge
cffi                      1.14.6           py38hd8c33c5_0    conda-forge
cfitsio                   3.470                h0af3d06_7    conda-forge
chardet                   4.0.0            py38haa244fe_1    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cryptography              3.4.7            py38hd7da0ea_0    conda-forge
curl                      7.78.0               h789b8ee_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
debugpy                   1.4.1            py38h885f38d_0    conda-forge
decorator                 5.0.9              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
expat                     2.4.1                h39d44d4_0    conda-forge
fontconfig                2.13.1            h1989441_1005    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
freexl                    1.0.6                ha8e266a_0    conda-forge
geos                      3.9.1                h39d44d4_2    conda-forge
geotiff                   1.6.0                hee96dd5_4    conda-forge
gettext                   0.19.8.1          h1a89ca6_1005    conda-forge
hdf4                      4.2.15               h0e5069d_3    conda-forge
hdf5                      1.10.6          nompi_h5268f04_1114    conda-forge
icu                       68.1                 h0e60522_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib-metadata        4.6.4            py38haa244fe_0    conda-forge
intel-openmp              2021.3.0          h57928b3_3372    conda-forge
ipykernel                 6.2.0            py38h595d716_0    conda-forge
ipython                   7.26.0           py38h595d716_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.18.0           py38haa244fe_2    conda-forge
jinja2                    3.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.1            py38haa244fe_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
kealib                    1.4.14               h96bfa42_2    conda-forge
kiwisolver                1.3.1            py38hbd9d945_1    conda-forge
krb5                      1.19.2               hbae68bd_0    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
libblas                   3.9.0              11_win64_mkl    conda-forge
libcblas                  3.9.0              11_win64_mkl    conda-forge
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libcurl                   7.78.0               h789b8ee_0    conda-forge
libffi                    3.3                  h0e60522_2    conda-forge
libgdal                   3.2.1                hca2c63a_7    conda-forge
libglib                   2.68.3               h1e62bf3_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libkml                    1.3.0             h9859afa_1014    conda-forge
liblapack                 3.9.0              11_win64_mkl    conda-forge
libnetcdf                 4.7.4           nompi_h3a9aa94_107    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libpq                     13.3                 hfcc5ef8_0    conda-forge
librttopo                 1.1.0                hb340de5_6    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libspatialite             5.0.1                h987baeb_3    conda-forge
libssh2                   1.9.0                h680486a_6    conda-forge
libtiff                   4.2.0                h763f289_2    conda-forge
libwebp-base              1.2.0                h8ffe710_2    conda-forge
libxml2                   2.9.12               hf5bbc77_0    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
markupsafe                2.0.1            py38h294d835_0    conda-forge
matplotlib                3.4.1            py38haa244fe_0    conda-forge
matplotlib-base           3.4.1            py38heae8d8c_0    conda-forge
matplotlib-inline         0.1.2              pyhd8ed1ab_2    conda-forge
mistune                   0.8.4           py38h294d835_1004    conda-forge
mkl                       2021.3.0           hb70f87d_564    conda-forge
nbclient                  0.5.3              pyhd8ed1ab_0    conda-forge
nbconvert                 6.1.0            py38haa244fe_0    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
notebook                  6.3.0              pyha770c72_1    conda-forge
numpy                     1.21.2           py38h089cfbf_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openssl                   1.1.1k               h8ffe710_0    conda-forge
packaging                 21.0               pyhd8ed1ab_0    conda-forge
pandas                    1.2.4            py38h60cbd38_0    conda-forge
pandoc                    2.14.1               h8ffe710_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.8.2              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h0e60522_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.2.0            py38h9273828_1    conda-forge
pip                       21.2.4             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h8ffe710_0    conda-forge
poppler                   0.89.0               h3772339_5    conda-forge
poppler-data              0.4.10                        0    conda-forge
postgresql                13.3                 h1c22c4f_0    conda-forge
proj                      7.2.0                h1cfcee9_2    conda-forge
prometheus_client         0.11.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.19             pyha770c72_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.10.0             pyhd8ed1ab_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    3.0.1            py38h0ae89ba_0    conda-forge
pyqt                      5.12.3           py38haa244fe_7    conda-forge
pyqt-impl                 5.12.3           py38h885f38d_7    conda-forge
pyqt5-sip                 4.19.18          py38h885f38d_7    conda-forge
pyqtchart                 5.12             py38h885f38d_7    conda-forge
pyqtwebengine             5.12.1           py38h885f38d_7    conda-forge
pyrsistent                0.17.3           py38h294d835_2    conda-forge
pysocks                   1.7.1            py38haa244fe_3    conda-forge
python                    3.8.8           h7840368_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-dotenv             0.17.1             pyhd8ed1ab_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pywin32                   301              py38h294d835_0    conda-forge
pywinpty                  1.1.3            py38hd3f51b4_0    conda-forge
pyzmq                     22.2.1           py38h09162b1_0    conda-forge
qt                        5.12.9               h5909a2a_4    conda-forge
rasterio                  1.2.3            py38h4f558c9_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                57.4.0           py38haa244fe_0    conda-forge
shapely                   1.7.1            py38h127f298_5    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sqlite                    3.36.0               h8ffe710_0    conda-forge
tbb                       2021.3.0             h2d74725_0    conda-forge
terminado                 0.10.1           py38haa244fe_0    conda-forge
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
tiledb                    2.2.9                hf84e3da_0    conda-forge
tk                        8.6.10               h8ffe710_1    conda-forge
tornado                   6.1              py38h294d835_1    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
urllib3                   1.26.6             pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_5    conda-forge
vs2015_runtime            14.29.30037          h902a5da_5    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
win_inet_pton             1.1.0            py38haa244fe_2    conda-forge
winpty                    0.4.3                         4    conda-forge
xerces-c                  3.2.3                h0e60522_2    conda-forge
xmltodict                 0.12.0                     py_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
zeromq                    4.3.4                h0e60522_0    conda-forge
zipp                      3.5.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge
zstd                      1.4.9                h6255e5f_0    conda-forge`

conda version:
`>conda --version
conda 4.9.2`

python:
`>python --version
Python 3.8.8`

jupyter error:
`>jupyter notebook
usage: jupyter-notebook.EXE [-h] [-V] command ...

conda is a tool for managing and deploying applications, environments and packages.

Options:

positional arguments:
  command
    clean        Remove unused packages and caches.
    compare      Compare packages between conda environments.
    config       Modify configuration values in .condarc. This is modeled
                 after the git config command. Writes to the user .condarc
                 file (C:\Users\Thayward\.condarc) by default.
    create       Create a new conda environment from a list of specified
                 packages.
    help         Displays a list of available conda commands and their help
                 strings.
    info         Display information about current conda install.
    init         Initialize conda for shell interaction. [Experimental]
    install      Installs a list of packages into a specified conda
                 environment.
    list         List linked packages in a conda environment.
    package      Low-level conda package utility. (EXPERIMENTAL)
    proswap      Set a new environment as the default for ArcGIS Pro.
    remove       Remove a list of packages from a specified conda environment.
    uninstall    Alias for conda remove.
    run          Run an executable in a conda environment. [Experimental]
    search       Search for packages and display associated information. The
                 input is a MatchSpec, a query language for conda packages.
                 See examples below.
    update       Updates conda packages to the latest compatible version.
    upgrade      Alias for conda update.

optional arguments:
  -h, --help     Show this help message and exit.
  -V, --version  Show the conda version number and exit.`

thanks
ty

**Comment by samfranklin** [comment]
@tyhayward thanks for the feedback on this, and glad you found workaround.

Unfortunately, we cannot fully support (i.e. test) the environment you're using, since it requires a commercial licence (arcgis pro).

I'll make an edit to the repo readme regarding running from a python environment within ArcGIS pro to the effect of "you might need to experiement with the jupyter notebook version". The curernt enironment.yml does work for the supported environments (windows+minconda, linux+virtualenv, docker) so we will not make any changes just now.

We'll aim to do an update of the packages too in a subsequent release of eodslib when we have capacity to test across all the supported environments.

I will close this ticket and add a backlog item for us to update the README. Thanks again.
