### ISSUE TITLE
searching for scenes using EODS parameters fail inconsistently with differing dates - split granules issue

### ISSUE THREAD

**Issue by tyhayward** [defra-data/EODS-API#7]
When attempting to search for 'best available' scenes using eods parameters the function falls over and throws exceptions/ 

I have previously downloaded the 'best available' s2 scenes across England for the month of May 2020 (2020-05-01 start, end 2020-05-31) using this environment and the same notebook so it is not a configuration issue. 

If I attempt to search again for May 2020 it works fine: 
![image](https://user-images.githubusercontent.com/54058249/129555301-75214125-3471-4b5b-86c8-ed798a123f8a.png)

if i attempt to search for May 2021 it throws a key error (restarted kernel) 
![image](https://user-images.githubusercontent.com/54058249/129555588-0b5d3efd-b091-4662-9475-57a4cd641f3f.png)

it throws this key error for every month in 2021 yet for 2020 the same parameters work fine. it seems this error was addressed 17 days ago by @samfranklin although the eodslib.py I am using was downloaded last week. 

I have tried adding in the optional parameter:
 'ignore_split_granules':True 
but this throws the same error:
![image](https://user-images.githubusercontent.com/54058249/129558965-7eb26b4e-5976-4d33-acba-109b47a4a27f.png)

https://github.com/defra-data/EODS-API/commit/59abeadda9c6210633a6ad9284b7bb5e3e6c8ec5 

Any help would be much appreciated as this has made the API unusable for 2021 data

Thanks,
Ty

**Comment by henrywild** [comment]
Hi @tyhayward,

Could you please share the WKT geometry you're searching with, for us to replicate this issue?

Thanks,
Henry

**Comment by tyhayward** [comment]
Hi @henrywild 

POLYGON((-3.77133801311454 54.76078615983,-2.98384818329618 51.4613262135595,-4.36195538547831 51.2538678902686,-6.17072108834236 50.0604666140093,-5.19866332966032 49.8149646824189,1.12586436606839 50.727210663285,1.74109079561399 51.2307589492102,1.8641360815231 52.8204691734456,-1.92565872447776 56.0461501889442,-3.77133801311454 54.76078615983))

it is a rough outline of England - as you can see in the 2020 query it worked fine. 

thanks,
Ty

**Comment by henrywild** [comment]
Thanks @tyhayward. I'll take a look now.

**Comment by henrywild** [comment]
Hi @tyhayward,

A PR has been merged in that should fix this issue. Can you please confirm whether or not you are still encountering it?

**Comment by tyhayward** [comment]
hi @henrywild I have downloaded the new version of eodslib and it seems to be working now. I am running it on a July 21 S2 best scene composite and the parameters have been accepted and it returned a successful response. It is downloading now - I will test on other dates etc. and get back.

Many thanks,
Ty

**Comment by henrywild** [comment]
@tyhayward Glad to hear it appears to be working. Now this has been resolved could you please remove or otherwise censor the 3 images you shared in your 1st post as the urls present in each of them show your auth token?

**Comment by tyhayward** [comment]
@henrywild done

**Comment by henrywild** [comment]
@tyhayward Thanks!
